= ansible-role-shellcheck
Jonas Pammer <opensource@jonaspammer.at>;
:toc: left
:toclevels: 2
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://galaxy.ansible.com/jonaspammer/shellcheck[image:https://img.shields.io/badge/available%20on%20ansible%20galaxy-jonaspammer.shellcheck-brightgreen[Version on Galaxy]]
// Very Relevant Status Badges
https://github.com/JonasPammer/ansible-role-shellcheck/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-shellcheck/actions/workflows/ci.yml/badge.svg[Testing CI]]


An Ansible role for installing shellcheck, a static analysis tool for shell scripts.

[quote]
____
At first you're like "shellcheck is awesome" but then you're like "wtf are we still using bash"
____

toc::[]

[[meta]]
== 🔎 Metadata
Below you can find information on…

* the role's required Ansible version
* the role's supported platforms
* the role's https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-dependencies[role dependencies]

.link:meta/main.yml[]
[source,yaml]
----
include::meta/main.yml[]
----


[[requirements]]
== 📌 Requirements
// Any prerequisites that may not be covered by this role or Ansible itself should be mentioned here.
The Ansible User needs to be able to `become`.


The https://galaxy.ansible.com/community/general[`community.general` collection]
must be installed on the Ansible controller.


[[variables]]
== 📜 Role Variables
// A description of the settable variables for this role should go here
// and any variables that can/should be set via parameters to the role.
// Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.)
// should be mentioned here as well.

[source,yaml]
----
shellcheck_install_method: release
----
How to install shellcheck. One of:

"`system`":: Install using package manager of the system.
"`release`":: Install by linking an official pre-compiled binary to `/usr/local/bin/shellcheck`.
"`source`":: Compile from source on Host
+
[IMPORTANT]
NOT IMPLEMENTED YET.


=== Role Variables used by the `release`-installation-method

[source,yaml]
----
shellcheck_release: stable
----
https://github.com/koalaman/shellcheck/releases[shellcheck release] to use.
Special values "`latest`" and "`stable`" can be used.

[source,yaml]
----
shellcheck_release_checksum_check: false
----
Enables checking the checksum of the downloaded release file.

[source,yaml]
----
shellcheck_release_checksums:
  "darwin.x86_64":
  "linux.aarch64":
  "linux.armv6hf":
  "linux.x86_64":
----
https://docs.ansible.com/ansible/2.9/modules/get_url_module.html#parameter-checksum[Format of checksums]:
`<algorithm>:<checksum|url>`, e.g.
`checksum="sha256:D98291AC[...]B6DC7B97"`,
`checksum="sha256:http://example.com/path/sha256sum.txt"` -
See <<example_playbooks>>.


[[public_vars]]
== 📜 Facts/Variables defined by this role

Each variable listed in this section
is dynamically defined when executing this role (and can only be overwritten using `ansible.builtin.set_facts`) _and_
is meant to be used not just internally.


[[tags]]
== 🏷️ Tags

// Checkout https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/main/roles/server/README.md#tags
// for an awesome example of grouping tasks using tags

Tasks are tagged with the following
https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#adding-tags-to-roles[tags]:

[cols="1,1"]
|===
|Tag | Purpose

2+| This role does not have officially documented tags yet.

// | download-xyz
// |
// | install-prerequisites
// |
// | install
// |
// | create-xyz
// |
|===

You can use Ansible to skip tasks, or only run certain tasks by using these tags. By default, all tasks are run when no tags are specified.

[[dependencies]]
== 👫 Dependencies
// A list of other roles should go here,
// plus any details in regard to parameters that may need to be set for other roles,
// or variables that are used from other roles.



[[example_playbooks]]
== 📚 Example Playbook Usages
// Including examples of how to use this role in a playbook for common scenarios is always nice for users.

[NOTE]
====
This role is part of https://github.com/JonasPammer/ansible-roles[
many compatible purpose-specific roles of mine].

The machine needs to be prepared.
In CI, this is done in `molecule/default/prepare.yml`
which sources its soft dependencies from `requirements.yml`:

.link:molecule/default/prepare.yml[]
[source,yaml]
----
include::molecule/default/prepare.yml[]
----

The following diagram is a compilation of the "soft dependencies" of this role
as well as the recursive tree of their soft dependencies.

image:https://raw.githubusercontent.com/JonasPammer/ansible-roles/master/graphs/dependencies_shellcheck.svg[
requirements.yml dependency graph of jonaspammer.shellcheck]
====

.Minimum Viable Play (Install the version defined in this role's defaults)
====
[source,yaml]
----
roles:
    - role: jonaspammer.shellcheck
----
====

.Install a specific version of shellcheck
====
[source,yaml]
----
roles:
    - role: jonaspammer.shellcheck

vars:
    shellcheck_release: v0.8.0
    shellcheck_release_checksum_check: true
    shellcheck_release_checksums:
        "darwin.x86_64": "sha1:9bc3fce6784be81a2e6dc8a6019258ebb6782081"
        "linux.aarch64": "sha1:cf996b7980ac32ddf75b5f45e9f249501907082e"
        "linux.armv6hf": "sha1:9586a4a84185828cb285f1b743d88a317171f74f"
        "linux.x86_64": "sha1:c4a6087437fe65aacd8ec588ccf47574a5dc4254"
----
====

.Install shellcheck from the system package manger
====
[source,yaml]
----
roles:
    - role: jonaspammer.shellcheck

vars:
    shellcheck_install_method: system
----
====

.Install shellcheck by building the binary on the Host
====
[source,yaml]
----
roles:
    - role: jonaspammer.shellcheck

vars:
    shellcheck_install_method: source
----
====


[[tested-distributions]]
== 🧪 Tested Distributions

A role may work on different *distributions*, like Red Hat Enterprise Linux (RHEL),
even though there is no test for this exact distribution.

// good reference for what to follow -- most starred and pinned project of geerlingguy:
// https://github.com/geerlingguy/ansible-role-docker/blob/master/.github/workflows/ci.yml
|===
| OS Family | Distribution | Distribution Release Date | Distribution End of Life | Accompanying Docker Image

// https://endoflife.date/rocky-linux
| Rocky
| Rocky Linux 8 (https://www.howtogeek.com/devops/is-rocky-linux-the-new-centos/[RHEL/CentOS 8 in disguise])
| 2021-06
| 2029-05
| https://github.com/geerlingguy/docker-rockylinux8-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-rockylinux8-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Rocky
| Rocky Linux 9
| 2022-07
| 2032-05
| https://github.com/geerlingguy/docker-rockylinux9-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-rockylinux9-ansible/workflows/Build/badge.svg?branch=master[CI]]

// https://endoflife.date/fedora (13 Months)
| RedHat
| Fedora 39
| 2023-11
| 2024-12
| https://github.com/geerlingguy/docker-fedora39-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-fedora39-ansible/workflows/Build/badge.svg?branch=master[CI]]

// https://ubuntu.com/about/release-cycle
| Debian
| Ubuntu 20.04 LTS
| 2021-04
| 2025-04
| https://github.com/geerlingguy/docker-ubuntu2004-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu2004-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Ubuntu 22.04 LTS
| 2022-04
| 2027-04
| https://github.com/geerlingguy/docker-ubuntu2204-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu2204-ansible/workflows/Build/badge.svg?branch=master[CI]]

// https://wiki.debian.org/DebianReleases
// https://wiki.debian.org/LTS
| Debian
| Debian 11
| 2021-08
| 2024-06 (2026-06 LTS)
| https://github.com/geerlingguy/docker-debian11-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-debian11-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Debian 12
| 2023-06
| 2026-06 (2028-06 LTS)
| https://github.com/geerlingguy/docker-debian12-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-debian12-ansible/workflows/Build/badge.svg?branch=master[CI]]
|===


[[tested-ansible-versions]]
== 🧪 Tested Ansible versions

The tested ansible versions try to stay equivalent with the
https://github.com/ansible-collections/community.general#tested-with-ansible[
support pattern of Ansible's `community.general` collection].
As of writing this is:

* 2.13 (Ansible 6)
* 2.14 (Ansible 7)
* 2.15 (Ansible 8)
* 2.16 (Ansible 9)


[[development]]
== 📝 Development
// Badges about Conventions in this Project
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-shellcheck/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-shellcheck/master.svg[pre-commit.ci status]]
// image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing
https://open.vscode.dev/JonasPammer/ansible-role-shellcheck[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]

include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/JonasPammer/ansible-role-shellcheck/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/ansible-role-shellcheck/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----
