---
- name: output some generally helpful debug information about the provisioned machine
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: debug output machine facts
      ansible.builtin.include_tasks: ../resources/debug.yml

### Actual Role Verification Tasks:
- name: Verify
  hosts: all

  tasks:
    - name: Run 'shellcheck --version' (ansible.builtin.command).
      ansible.builtin.command: shellcheck --version
      changed_when: false

    - name: Fetch shellcheck version.
      ansible.builtin.shell: >
        set -o pipefail && \
        shellcheck --version | grep 'version: ' | awk '{ print $2 }'
      args:
        executable: /bin/bash
      changed_when: false
      register: shellcheck__register_shell_shellcheck_version_awk

    - name: Check shellcheck version.
      ansible.builtin.assert:
        that:
          - shellcheck__register_shell_shellcheck_version_awk.stdout == "0.8.0"
