---
# tasks file for testing that variables of ansible-role jonaspammer.shellcheck are set correctly
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html

- name: test if 'shellcheck_install_method' is set correctly
  ansible.builtin.assert:
    that:
      - shellcheck_install_method is defined
      - shellcheck_install_method in ["release", "source", "system"]
    quiet: true
