---
- name: output some generally helpful debug information about the provisioned machine
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: debug output machine facts
      ansible.builtin.include_tasks: ../resources/debug.yml

### Actual Role Verification Tasks:
- name: Verify
  hosts: all

  tasks:
    - name: create example bash file
      ansible.builtin.shell: |
        cat << EOF > /test.bash
        #!/bin/bash

        echo "hello"
        EOF
      changed_when: false

    - name: Run 'shellcheck --version' (ansible.builtin.command).
      ansible.builtin.command: shellcheck --version
      changed_when: false

    - name: Run 'shellcheck --version' (ansible.builtin.shell).
      ansible.builtin.shell: shellcheck --version # noqa command-instead-of-shell
      changed_when: false
