---
name: CI (Lint + Molecule)
permissions: read-all
"on":
  workflow_dispatch:
    inputs:
      lint:
        description: "Lint"
        required: true
        default: true
        type: boolean
  pull_request:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/ci.yml"
      - "defaults/*"
      - "handlers/*"
      - "meta/**"
      - "molecule/**"
      - "tasks/*"
      - "vars/*"
      - ".gitattributes"
      - ".yamllint"
      - "pyproject.toml"
      - "requirements.yml"
      - "tox.ini"
  schedule:
    # At 05:00 on Sunday.
    - cron: "0 5 * * 0"

jobs:
  lint:
    name: Lint
    if: ${{ github.event.inputs.lint != 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint YAML (GitHub Annotations)
        run: |
          cat <<HEREDOC
          Wondering about why there are no file names?
          This command outputs information parsed by GitHub
          to be displayed in 'Annotations' tab.
          HEREDOC
          yamllint . -f github

      - name: Lint YAML (Standard Output)
        if: always()
        run: yamllint . -f standard
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - centos7
          - centos8
          - debian10
          - debian11
          - fedora35
          - rockylinux8
          - ubuntu1604
          - ubuntu1804
          - ubuntu2004

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install test dependencies.
        run: pip3 install tox~=3.24.5

      - name: Run Molecule tests (normal).
        run: tox
        env:
          MOLECULE_DISTRO: ${{ matrix.distro }}
          TOX_PARALLEL_NO_SPINNER: 1
        if: ${{ github.event_name != 'workflow_dispatch' }}

      - name: Run Molecule tests (debug).
        run: tox
        env:
          MOLECULE_DESTROY: never
          MOLECULE_DISTRO: ${{ matrix.distro }}
          TOX_PARALLEL_NO_SPINNER: 1
        if: ${{ github.event_name == 'workflow_dispatch' }}

      - name: setup tmate session if previous step failed and if this is a manual run
        if: ${{ failure() && github.event_name == 'workflow_dispatch' }}
        uses: mxschmitt/action-tmate@v3
